### ISSUE TITLE
Not working in python 2.6.6

### ISSUE THREAD

**Issue by bkuberek** [kvesteri/wtforms-alchemy#35]
collections.OrderedDict was added in python 2.7 and thus an error is thrown when wtforms_alchemy tries to import it

```
...
  File "/path/to/project/forms.py", line 10, in <module>
    from wtforms_alchemy import model_form_factory
  File "/usr/local/lib/python2.6/dist-packages/wtforms_alchemy/__init__.py", line 23, in <module>
    from .generator import FormGenerator
  File "/usr/local/lib/python2.6/dist-packages/wtforms_alchemy/generator.py", line 2, in <module>
    from collections import OrderedDict
ImportError: cannot import name OrderedDict
```
